import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
};

const SYSTEM_PROMPT = `You are an expert forensic linguist and stylometry specialist. You will be given an array of paragraphs from a research paper. Your ONLY job is to analyze writing style consistency across paragraphs — NOT to detect plagiarism or AI generation, that is handled separately.

Analyze each paragraph for these exact stylometric features:
- Sentence length variance (average words per sentence, standard deviation)
- Syntactic complexity (clause depth, subordinate clause frequency)
- Type-token ratio (unique words / total words — measure of vocabulary richness)
- Passive vs active voice ratio
- Transition word density and types used (additive, causal, contrastive, sequential)
- Hedging language frequency (words like "may", "might", "could", "suggest", "appears")
- Punctuation density (commas, semicolons, colons per 100 words)
- Academic register markers (Latinate vocabulary, nominalization patterns)
- Paragraph internal structure (topic sentence clarity, evidence-argument pattern)
- Cohesion with surrounding paragraphs (does this paragraph connect naturally)

Flagging rules — flag a paragraph as true if ANY of these apply:
- consistency_score below 0.75
- Tone differs significantly from document majority tone
- Vocabulary richness level differs by more than one level from majority
- Passive voice ratio is an outlier compared to rest of document
- Transition word pattern is completely different from surrounding paragraphs
- Paragraph feels stylistically isolated from its neighbors

Cluster paragraphs by writing style. Paragraphs with statistically similar stylometric profiles belong to the same cluster. Label clusters A, B, C, D etc. The majority cluster is the dominant writing style of the document.

Return ONLY valid JSON, no explanation, no markdown, no backticks:
{
  "paragraphs": [
    {
      "id": 1,
      "cluster": "A",
      "consistency_score": 0.91,
      "tone": "formal",
      "vocabulary_richness": "high",
      "sentence_length": "long",
      "passive_voice_ratio": "high",
      "transition_density": "medium",
      "hedging_frequency": "high",
      "flagged": false,
      "flag_reason": "null if not flagged, otherwise specific linguistic reason why this paragraph stands out"
    }
  ],
  "integrity_score": 0.0-100.0,
  "cluster_count": number,
  "dominant_cluster": "A",
  "cluster_profiles": {
    "A": "description of the writing style of this cluster with specific linguistic features",
    "B": "description of writing style of cluster B"
  },
  "verdict": "Consistent Style" | "Minor Inconsistencies ⚠️" | "Significant Style Shifts 🚨",
  "summary": "4-5 sentence forensic summary describing which paragraphs shifted, what specific stylometric features changed, what this pattern suggests about the document, and which paragraph ranges are most suspicious."
}

IMPORTANT: Two paragraphs can both be formal and academic in tone but still belong to different clusters if they show different micro-level patterns such as transition word choices, paragraph internal structure, sentence length uniformity, or hedging frequency. Do not group paragraphs into the same cluster just because they share the same general academic register. Look for subtle differences in rhythm, structure, and word choice patterns. A document where one paragraph consistently uses "Furthermore/Moreover" transitions and another uses "However/Nevertheless" transitions should be flagged as different clusters even if both are formal.

integrity_score = (non-flagged paragraphs / total paragraphs) * 100 rounded to 1 decimal.
cluster_count = number of distinct style clusters found.`;

const AI_DETECTOR_PROMPT = `You are the world's most accurate AI-generated content detector. Your job is to determine with maximum precision whether each paragraph was written by a human or generated by an AI language model such as ChatGPT, Claude, Gemini, Copilot, or any other LLM.

You must be extremely accurate. Do not over-flag human writing as AI. Do not miss genuine AI-generated content. Approach this like a forensic scientist — only flag what you can justify with specific linguistic evidence.

AI-generated content has these detectable signals — weight each heavily:

STRONG signals of AI generation (each raises score significantly):
- Perfectly balanced paragraph structure: setup sentence + exactly 2-3 supporting points + conclusion sentence
- Overuse of meta-commentary transition phrases: "it is worth noting", "it is important to", "furthermore", "moreover", "in conclusion", "additionally", "this highlights", "this underscores", "this demonstrates"
- Unnaturally consistent sentence length throughout — human writers vary dramatically, AI maintains uniformity
- Generic academic vocabulary without domain-specific depth or personal expertise showing
- Absence of hedging uncertainty typical of genuine researchers ("we observed", "our results suggest", "surprisingly")
- No citations or vague citation patterns like "studies have shown" without specifics
- Perfectly symmetrical argument structure across paragraphs
- Lack of any personal research voice, opinion, or unique insight
- Suspiciously clean grammar with zero idiosyncratic phrasing

WEAK signals of AI generation (raise score slightly):
- Formal tone throughout
- Clear logical structure
- Good vocabulary range

STRONG signals of HUMAN writing (each lowers score significantly):
- Idiosyncratic phrasing or unusual word choices
- Irregular sentence rhythm with genuine variation
- Personal research observations and specific data references
- Domain expertise showing through precise technical terminology
- Natural hedging and uncertainty markers
- Self-referential statements about the research process
- Occasional awkward constructions that a human would write
- Specific citations with precise details

TOOL-SPECIFIC FINGERPRINTS — use these to identify which AI generated the content:

ChatGPT/GPT-4 signals:
- Frequently starts paragraphs with "Certainly", "Of course", "It is worth noting"
- Uses numbered or bulleted internal structure even in prose
- Heavy use of "Furthermore", "Moreover", "In addition" as paragraph starters
- Tends toward perfectly balanced 4-5 sentence paragraphs
- Uses "delve", "tapestry", "nuanced", "multifaceted", "crucial" frequently
- Ends paragraphs with a summary or conclusion sentence restating the main point

Gemini signals:
- More varied paragraph length than GPT
- Uses "it's important to", "plays a crucial role", "a key aspect"
- Slightly more conversational tone than GPT even in academic writing
- Uses bullet points or colons to introduce lists within paragraphs
- More likely to use present tense throughout

Claude signals:
- More hedging language: "may", "might", "could suggest", "appears to"
- Uses em dashes — like this — more frequently
- More likely to acknowledge limitations or counterarguments
- Slightly more varied sentence length than GPT or Gemini
- Uses "I" or first person more naturally even in academic contexts

Human academic writing signals:
- Irregular sentence rhythm with genuine variation
- Specific data references with precise numbers and citations
- Idiosyncratic phrasing unique to the author
- Occasional grammatical awkwardness
- Personal research observations and hedged conclusions
- Domain expertise showing through precise technical terminology

For each paragraph produce an ai_score from 0-100:
- 0-25: Almost certainly human written
- 26-45: Likely human with possible AI assistance
- 46-65: Ambiguous, possibly AI assisted
- 66-85: Likely AI generated
- 86-100: Almost certainly AI generated

Be conservative — only score above 75 if you have multiple strong signals.

Return ONLY valid JSON, no explanation, no markdown, no backticks:
{
  "overall_ai_score": 0-100,
  "verdict": "Human Written ✅" | "Likely Human with AI Assistance ⚠️" | "Likely AI Generated 🤖" | "Almost Certainly AI Generated 🚨",
  "dominant_ai_tool": "ChatGPT" | "Claude" | "Gemini" | "Copilot" | "Unknown AI" | "None",
  "ai_percentage": 0-100,
  "paragraphs": [
    {
      "id": 1,
      "ai_score": 0-100,
      "verdict": "Human" | "Likely Human" | "Ambiguous" | "Likely AI" | "AI Generated",
      "confidence": "low" | "medium" | "high",
      "signals_detected": ["specific signal 1 found in this paragraph", "specific signal 2"],
      "human_signals_detected": ["specific human signal found if any"],
      "reasoning": "2-3 sentence specific explanation of exactly why this score was assigned with direct references to the text"
    }
  ],
  "most_suspicious_paragraphs": [1, 3, 7],
  "summary": "4-5 sentence forensic summary. State the overall AI score, identify which specific paragraphs are most suspicious, cite the exact linguistic signals that drove the verdict, identify the likely AI tool if detectable, and give a final conclusion about the document's authenticity."
}

overall_ai_score = weighted average of all paragraph ai_scores.
ai_percentage = percentage of paragraphs with ai_score above 65.`;

const GEMINI_MODELS = [
  "gemini-2.5-flash",
  "gemini-2.0-flash",
  "gemini-2.0-flash-lite"
];

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

async function runGemini(apiKey: string, userMessage: string, useDetectorPrompt = false) {
  const prompt = useDetectorPrompt ? AI_DETECTOR_PROMPT : SYSTEM_PROMPT;

  for (const model of GEMINI_MODELS) {
    let attempts = 0;
    while (attempts < 2) {
      attempts++;
      try {
        console.log(`[Gemini] Attempt ${attempts} using model: ${model}`);
        const response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              contents: [{ parts: [{ text: prompt + "\n\n" + userMessage }] }],
              generationConfig: {
                temperature: 0.05,
                maxOutputTokens: 8192,
                responseMimeType: "application/json"
              }
            })
          }
        );

        if (response.status === 404 || response.status === 503) {
          console.log(`[Gemini] Model ${model} unavailable (${response.status}), trying next...`);
          break;
        }

        if (response.status === 429) {
          if (attempts < 2) { await sleep(1000); continue; }
          break;
        }

        if (!response.ok) {
          console.log(`[Gemini] Model ${model} error (${response.status}), trying next...`);
          break;
        }

        const data = await response.json();
        const rawContent = data.candidates?.[0]?.content?.parts?.[0]?.text || "{}";
        console.log(`[Gemini] Success with ${model}`);
        return JSON.parse(rawContent);

      } catch (e) {
        console.error(`[Gemini] Error on ${model} attempt ${attempts}:`, e.message);
        if (attempts < 2) { await sleep(500); continue; }
        break;
      }
    }
  }
  throw new Error('All Gemini models failed');
}

async function runGroq(apiKey: string, userMessage: string) {
  console.log(`[Groq] Starting analysis...`);
  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userMessage }
      ],
      temperature: 0.1,
      max_tokens: 4000
    })
  });

  if (!response.ok) {
    const errText = await response.text();
    console.error(`[Groq] API Error ${response.status}:`, errText);
    throw new Error(`Groq API Error: ${response.status}`);
  }

  const data = await response.json();
  const rawContent = data.choices?.[0]?.message?.content || "{}";
  const cleaned = rawContent.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
  console.log(`[Groq] Analysis successful`);
  return JSON.parse(cleaned);
}

async function searchSemanticScholar(query: string) {
  const response = await fetch(
    `https://api.semanticscholar.org/graph/v1/paper/search?query=${encodeURIComponent(query)}&fields=title,authors,year,venue,citationCount,externalIds,abstract&limit=3`,
    {
      headers: { 'Accept': 'application/json' },
      signal: AbortSignal.timeout(10000)
    }
  );
  if (!response.ok) {
    console.warn(`[Source Tracing] Semantic Scholar returned ${response.status}`);
    return { data: [] };
  }
  return await response.json();
}

async function searchArxiv(query: string) {
  const response = await fetch(
    `https://export.arxiv.org/api/query?search_query=all:${encodeURIComponent(query)}&max_results=2`,
    { signal: AbortSignal.timeout(10000) }
  );
  return await response.text();
}

console.log('[Analyze Function] Starting up...');
console.log('[Analyze Function] GEMINI_API_KEY present:', !!Deno.env.get('GEMINI_API_KEY'));
console.log('[Analyze Function] GROQ_API_KEY present:', !!Deno.env.get('GROQ_API_KEY'));
console.log('[Analyze Function] SYSTEM_PROMPT length:', SYSTEM_PROMPT.length);
console.log('[Analyze Function] AI_DETECTOR_PROMPT length:', AI_DETECTOR_PROMPT.length);

serve(async (req) => {
  // This MUST be first — before any await or try/catch
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { action, userMessage, paragraphs, searchQuery, source } = await req.json();

    const geminiApiKey = Deno.env.get('GEMINI_API_KEY') || '';
    const groqApiKey = Deno.env.get('GROQ_API_KEY') || '';
    const charCount = userMessage?.length || 0;

    // Action: stylometry analysis
    if (action === 'stylometry') {
      let result;
      if (charCount < 3000) {
        console.log('[Analyze] Small file — using Groq');
        try {
          result = await runGroq(groqApiKey, userMessage);
        } catch {
          console.log('[Analyze] Groq failed, falling back to Gemini');
          result = await runGemini(geminiApiKey, userMessage);
        }
      } else {
        console.log('[Analyze] Large file — using Gemini');
        try {
          result = await runGemini(geminiApiKey, userMessage);
        } catch {
          console.log('[Analyze] Gemini failed, falling back to Groq');
          result = await runGroq(groqApiKey, userMessage);
        }
      }
      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Action: AI detection
    if (action === 'ai-detection') {
      try {
        const userMsg = paragraphs
          .map((p: string, i: number) => `Paragraph ${i + 1}:\n${p}`)
          .join('\n\n');

        console.log(`[AI Detection] Analyzing ${paragraphs.length} paragraphs...`);
        const result = await runGemini(geminiApiKey, userMsg, true);
        console.log('[AI Detection] Success:', JSON.stringify(result).substring(0, 100));

        return new Response(JSON.stringify(result), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      } catch (error) {
        console.error('[AI Detection] Failed:', error.message);
        return new Response(JSON.stringify({
          error: error.message,
          overall_ai_score: 0,
          verdict: "Analysis Unavailable",
          paragraphs: [],
          summary: "AI detection failed. Please try again."
        }), {
          status: 200,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
    }

    // Action: source tracing
    if (action === 'source-tracing') {
      if (source === 'semantic-scholar') {
        const data = await searchSemanticScholar(searchQuery);
        return new Response(JSON.stringify(data), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
      if (source === 'arxiv') {
        const xml = await searchArxiv(searchQuery);
        return new Response(JSON.stringify({ xml }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
    }

    // Action: extract-query (for source tracing query extraction via Gemini)
    if (action === 'extract-query') {
      const result = await runGeminiRaw(geminiApiKey, userMessage);
      return new Response(JSON.stringify({ query: result }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    return new Response(JSON.stringify({ error: 'Invalid action' }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('[Analyze Function] Error:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});

// Raw Gemini call for simple text extraction (no JSON mode)
async function runGeminiRaw(apiKey: string, prompt: string): Promise<string> {
  for (const model of GEMINI_MODELS) {
    try {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: { temperature: 0.1, maxOutputTokens: 100 }
          })
        }
      );
      if (!response.ok) continue;
      const data = await response.json();
      return data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || '';
    } catch {
      continue;
    }
  }
  throw new Error('All Gemini models failed for raw extraction');
}
