import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
};

const SYSTEM_PROMPT = `You are an expert forensic linguist and stylometry specialist. You will be given an array of paragraphs from a research paper. Your ONLY job is to analyze writing style consistency across paragraphs — NOT to detect plagiarism or AI generation, that is handled separately.

Analyze each paragraph for these exact stylometric features:
- Sentence length variance (average words per sentence, standard deviation)
- Syntactic complexity (clause depth, subordinate clause frequency)
- Type-token ratio (unique words / total words — measure of vocabulary richness)
- Passive vs active voice ratio
- Transition word density and types used (additive, causal, contrastive, sequential)
- Hedging language frequency (words like "may", "might", "could", "suggest", "appears")
- Punctuation density (commas, semicolons, colons per 100 words)
- Academic register markers (Latinate vocabulary, nominalization patterns)
- Paragraph internal structure (topic sentence clarity, evidence-argument pattern)
- Cohesion with surrounding paragraphs (does this paragraph connect naturally)

Flagging rules — flag a paragraph as true if ANY of these apply:
- consistency_score below 0.75
- Tone differs significantly from document majority tone
- Vocabulary richness level differs by more than one level from majority
- Passive voice ratio is an outlier compared to rest of document
- Transition word pattern is completely different from surrounding paragraphs
- Paragraph feels stylistically isolated from its neighbors

Cluster paragraphs by writing style. Paragraphs with statistically similar stylometric profiles belong to the same cluster. Label clusters A, B, C, D etc. The majority cluster is the dominant writing style of the document.

Return ONLY valid JSON, no explanation, no markdown, no backticks:
{
  "paragraphs": [
    {
      "id": 1,
      "cluster": "A",
      "consistency_score": 0.91,
      "tone": "formal",
      "vocabulary_richness": "high",
      "sentence_length": "long",
      "passive_voice_ratio": "high",
      "transition_density": "medium",
      "hedging_frequency": "high",
      "flagged": false,
      "flag_reason": "null if not flagged, otherwise specific linguistic reason why this paragraph stands out"
    }
  ],
  "integrity_score": 0.0-100.0,
  "cluster_count": number,
  "dominant_cluster": "A",
  "cluster_profiles": {
    "A": "description of the writing style of this cluster with specific linguistic features",
    "B": "description of writing style of cluster B"
  },
  "verdict": "Consistent Style" | "Minor Inconsistencies ⚠️" | "Significant Style Shifts 🚨",
  "summary": "4-5 sentence forensic summary describing which paragraphs shifted, what specific stylometric features changed, what this pattern suggests about the document, and which paragraph ranges are most suspicious."
}

IMPORTANT: Two paragraphs can both be formal and academic in tone but still belong to different clusters if they show different micro-level patterns such as transition word choices, paragraph internal structure, sentence length uniformity, or hedging frequency. Do not group paragraphs into the same cluster just because they share the same general academic register. Look for subtle differences in rhythm, structure, and word choice patterns. A document where one paragraph consistently uses "Furthermore/Moreover" transitions and another uses "However/Nevertheless" transitions should be flagged as different clusters even if both are formal.

integrity_score = (non-flagged paragraphs / total paragraphs) * 100 rounded to 1 decimal.
cluster_count = number of distinct style clusters found.`;

const AI_DETECTOR_PROMPT = `You are the world's most accurate AI-generated content detector. Your job is to determine with maximum precision whether each paragraph was written by a human or generated by an AI language model such as ChatGPT, Claude, Gemini, Copilot, or any other LLM.

You must be extremely accurate. Do not over-flag human writing as AI. Do not miss genuine AI-generated content. Approach this like a forensic scientist — only flag what you can justify with specific linguistic evidence.

AI-generated content has these detectable signals — weight each heavily:

STRONG signals of AI generation (each raises score significantly):
- Perfectly balanced paragraph structure: setup sentence + exactly 2-3 supporting points + conclusion sentence
- Overuse of meta-commentary transition phrases: "it is worth noting", "it is important to", "furthermore", "moreover", "in conclusion", "additionally", "this highlights", "this underscores", "this demonstrates"
- Unnaturally consistent sentence length throughout — human writers vary dramatically, AI maintains uniformity
- Generic academic vocabulary without domain-specific depth or personal expertise showing
- Absence of hedging uncertainty typical of genuine researchers ("we observed", "our results suggest", "surprisingly")
- No citations or vague citation patterns like "studies have shown" without specifics
- Perfectly symmetrical argument structure across paragraphs
- Lack of any personal research voice, opinion, or unique insight
- Suspiciously clean grammar with zero idiosyncratic phrasing

WEAK signals of AI generation (raise score slightly):
- Formal tone throughout
- Clear logical structure
- Good vocabulary range

STRONG signals of HUMAN writing (each lowers score significantly):
- Idiosyncratic phrasing or unusual word choices
- Irregular sentence rhythm with genuine variation
- Personal research observations and specific data references
- Domain expertise showing through precise technical terminology
- Natural hedging and uncertainty markers
- Self-referential statements about the research process
- Occasional awkward constructions that a human would write
- Specific citations with precise details

TOOL-SPECIFIC FINGERPRINTS — use these to identify which AI generated the content:

ChatGPT/GPT-4 signals:
- Frequently starts paragraphs with "Certainly", "Of course", "It is worth noting"
- Uses numbered or bulleted internal structure even in prose
- Heavy use of "Furthermore", "Moreover", "In addition" as paragraph starters
- Tends toward perfectly balanced 4-5 sentence paragraphs
- Uses "delve", "tapestry", "nuanced", "multifaceted", "crucial" frequently
- Ends paragraphs with a summary or conclusion sentence restating the main point

Gemini signals:
- More varied paragraph length than GPT
- Uses "it's important to", "plays a crucial role", "a key aspect"
- Slightly more conversational tone than GPT even in academic writing
- Uses bullet points or colons to introduce lists within paragraphs
- More likely to use present tense throughout

Claude signals:
- More hedging language: "may", "might", "could suggest", "appears to"
- Uses em dashes — like this — more frequently
- More likely to acknowledge limitations or counterarguments
- Slightly more varied sentence length than GPT or Gemini
- Uses "I" or first person more naturally even in academic contexts

Human academic writing signals:
- Irregular sentence rhythm with genuine variation
- Specific data references with precise numbers and citations
- Idiosyncratic phrasing unique to the author
- Occasional grammatical awkwardness
- Personal research observations and hedged conclusions
- Domain expertise showing through precise technical terminology

For each paragraph produce an ai_score from 0-100:
- 0-25: Almost certainly human written
- 26-45: Likely human with possible AI assistance
- 46-65: Ambiguous, possibly AI assisted
- 66-85: Likely AI generated
- 86-100: Almost certainly AI generated

Be conservative — only score above 75 if you have multiple strong signals.

Return ONLY valid JSON, no explanation, no markdown, no backticks:
{
  "overall_ai_score": 0-100,
  "verdict": "Human Written ✅" | "Likely Human with AI Assistance ⚠️" | "Likely AI Generated 🤖" | "Almost Certainly AI Generated 🚨",
  "dominant_ai_tool": "ChatGPT" | "Claude" | "Gemini" | "Copilot" | "Unknown AI" | "None",
  "ai_percentage": 0-100,
  "paragraphs": [
    {
      "id": 1,
      "ai_score": 0-100,
      "verdict": "Human" | "Likely Human" | "Ambiguous" | "Likely AI" | "AI Generated",
      "confidence": "low" | "medium" | "high",
      "signals_detected": ["specific signal 1 found in this paragraph", "specific signal 2"],
      "human_signals_detected": ["specific human signal found if any"],
      "reasoning": "2-3 sentence specific explanation of exactly why this score was assigned with direct references to the text"
    }
  ],
  "most_suspicious_paragraphs": [1, 3, 7],
  "summary": "4-5 sentence forensic summary. State the overall AI score, identify which specific paragraphs are most suspicious, cite the exact linguistic signals that drove the verdict, identify the likely AI tool if detectable, and give a final conclusion about the document's authenticity."
}

overall_ai_score = weighted average of all paragraph ai_scores.
ai_percentage = percentage of paragraphs with ai_score above 65.`;

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

async function runGroq(apiKey: string, userMessage: string, useDetectorPrompt = false) {
  const systemPrompt = useDetectorPrompt ? AI_DETECTOR_PROMPT : SYSTEM_PROMPT;
  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userMessage }
      ],
      temperature: 0.1,
      max_tokens: 4000
    })
  });
  if (!response.ok) {
    const errText = await response.text();
    console.error(`[Groq] API Error ${response.status}:`, errText);
    throw new Error(`Groq API Error: ${response.status}`);
  }
  const data = await response.json();
  const rawContent = data.choices?.[0]?.message?.content || "{}";
  const cleaned = rawContent.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
  return JSON.parse(cleaned);
}

async function searchSemanticScholar(query: string) {
  const response = await fetch(
    `https://api.semanticscholar.org/graph/v1/paper/search?query=${encodeURIComponent(query)}&fields=title,authors,year,venue,citationCount,externalIds,abstract&limit=3`,
    {
      headers: { 'Accept': 'application/json' },
      signal: AbortSignal.timeout(10000)
    }
  );
  if (!response.ok) {
    console.warn(`[Source Tracing] Semantic Scholar returned ${response.status}`);
    return { data: [] };
  }
  return await response.json();
}

async function searchArxiv(query: string) {
  const response = await fetch(
    `https://export.arxiv.org/api/query?search_query=all:${encodeURIComponent(query)}&max_results=2`,
    { signal: AbortSignal.timeout(10000) }
  );
  return await response.text();
}

// Helper to parse Arxiv XML search results
function parseArxivXml(xml: string) {
  const papers = [];
  try {
    const entries = xml.split('<entry>');
    for (let i = 1; i < entries.length; i++) {
       const title = entries[i].match(/<title>([\s\S]*?)<\/title>/)?.[1]?.replace(/\n/g, ' ').trim() || 'Unknown Title';
       const link = entries[i].match(/<id>([\s\S]*?)<\/id>/)?.[1]?.trim() || '';
       const authors = [...entries[i].matchAll(/<name>([\s\S]*?)<\/name>/g)].map(m => m[1]).join(', ');
       papers.push({ title, link, authors });
    }
  } catch (e) {
    console.error('[Arxiv Parse] Error:', e);
  }
  return papers;
}

async function runGroqRaw(apiKey: string, prompt: string): Promise<string> {
  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.1,
      max_tokens: 50
    })
  });
  if (!response.ok) throw new Error(`Groq raw error: ${response.status}`);
  const data = await response.json();
  return data.choices?.[0]?.message?.content?.trim() || '';
}

console.log('[Analyze Function] Starting up...');
console.log('[Analyze Function] GROQ_API_KEY present:', !!Deno.env.get('GROQ_API_KEY'));
console.log('[Analyze Function] SYSTEM_PROMPT length:', SYSTEM_PROMPT.length);
console.log('[Analyze Function] AI_DETECTOR_PROMPT length:', AI_DETECTOR_PROMPT.length);

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { action, userMessage, paragraphs } = await req.json();

    const groqKey = Deno.env.get('GROQ_API_KEY') || '';

    // Unified Action payload
    if (action === 'analyze') {
      const out = {
        success: true,
        stylometry: null as any,
        aiDetection: null as any,
        sourceTracing: null as any,
        warnings: [] as string[]
      };

      // 1. INPUT PROCESSING
      let parsedParagraphs: string[] = [];
      if (paragraphs && Array.isArray(paragraphs)) {
        parsedParagraphs = paragraphs.map((p: any) => typeof p === 'string' ? p : p.text).filter(Boolean);
      } else if (userMessage) {
        parsedParagraphs = userMessage.split(/\n\s*\n/).map((p: string) => p.trim()).filter((p: string) => p.length > 20);
      }

      // Normalize whitespace and deduplicate
      parsedParagraphs = parsedParagraphs.map(p => p.replace(/\s+/g, ' ').trim());

      let selectedParagraphs = parsedParagraphs;
      if (parsedParagraphs.length > 5) {
        const intro = parsedParagraphs.slice(0, 2);
        const midIdx = Math.floor(parsedParagraphs.length / 2);
        const mid = parsedParagraphs.slice(midIdx, midIdx + 1);
        const conclusion = parsedParagraphs.slice(-2);
        selectedParagraphs = [...intro, ...mid, ...conclusion];
      }
      
      // Fallback: if subsampling is too aggressive, use full text
      if (selectedParagraphs.length < 2 && parsedParagraphs.length > 0) {
        selectedParagraphs = parsedParagraphs;
      }

      let userMsg = selectedParagraphs.map((p, i) => `Paragraph ${i + 1}:\n${p}`).join('\n\n');
      if (userMsg.length > 4500) {
        userMsg = userMsg.slice(0, 4500) + "\n\n[TRUNCATED FOR LIMIT]";
      }

      // 2. STYLOMETRY (Mathematical)
      try {
        const metricsArr: any[] = [];
        selectedParagraphs.forEach((text, i) => {
          const sentences = text.match(/[^.!?]+[.!?]+/g) || [text];
          const words = text.toLowerCase().match(/\b\w+\b/g) || [];
          if (words.length === 0) return;
          
          const avgSentenceLength = words.length / sentences.length;
          const uniqueWords = new Set(words).size;
          const vocabRichness = uniqueWords / words.length;
          const punctuationMatches = text.match(/[,;:\-\(\)\"'\[\]\{\}]/g) || [];
          const punctuationDensity = punctuationMatches.length / words.length;
          const passiveVoiceMatches = text.match(/\b(is|am|are|was|were|be|being|been)\s+[a-z]+ed\b/gi) || [];
          const passiveVoiceRatio = passiveVoiceMatches.length / sentences.length;

          metricsArr.push({
            id: i + 1, text: text, cluster: 1, flagged: false, metrics: { avgSentenceLength, vocabRichness, punctuationDensity, passiveVoiceRatio }, consistency_score: 0.95
          });
        });

        if (metricsArr.length > 0) {
          const stdDevs = ['avgSentenceLength', 'vocabRichness', 'punctuationDensity'].map(key => {
            const vals = metricsArr.map(m => m.metrics[key]);
            const mean = vals.reduce((a, b) => a + b, 0) / vals.length;
            const variance = vals.reduce((a, b) => a + Math.pow(b - mean, 2), 0) / vals.length;
            return Math.sqrt(variance || 0);
          });

          const variancePenalty = (stdDevs[0] * 2) + (stdDevs[1] * 100) + (stdDevs[2] * 200);
          let score = 100 - variancePenalty;
          if (score < 0) score = 0;
          if (score > 100) score = 100;

          let clusterCount = 1;
          if (score < 60) clusterCount = 3;
          else if (score < 80) clusterCount = 2;
          
          const meanSent = metricsArr.reduce((a, b) => a + b.metrics.avgSentenceLength, 0) / metricsArr.length;
          const analyzedParagraphs = metricsArr.map(p => {
              const isAnomaly = Math.abs(p.metrics.avgSentenceLength - meanSent) > 10;
              return {
                  ...p, cluster: clusterCount > 1 ? (isAnomaly ? 2 : 1) : 1, flagged: isAnomaly, consistency_score: isAnomaly ? 0.6 : Math.min(1.0, score / 100 + 0.1)
              }
          });

          let verdict = "✅ Low Risk — Document Appears Authentic and Consistent";
          if (score < 60) verdict = "🚨 HIGH RISK — Multiple Authors Detected";
          else if (score < 80) verdict = "⚠️ MODERATE RISK — Style Inconsistencies Detected";

          out.stylometry = {
            integrity_score: Math.round(score), 
            cluster_count: clusterCount, 
            verdict: verdict, 
            summary: `Analyzed mathematically. Overall integrity score is ${Math.round(score)}/100.`, 
            paragraphs: analyzedParagraphs
          };
        } else {
           out.warnings.push("Not enough parsable text for stylometry.");
        }
      } catch (e) {
        out.warnings.push("Stylometry failed");
      }

      // 3. AI DETECTION (Single Call)
      try {
        if (selectedParagraphs.length > 0) {
          console.log(`[AI Detection] Analyzing with Groq...`);
          const groqKey = Deno.env.get('GROQ_API_KEY') || '';
          const result = await runGroq(groqKey, userMsg, true);
          if (result && (result.overall_ai_score === 0 || result.overall_ai_score === undefined)) {
            result.overall_ai_score = null;
          }
          out.aiDetection = result;
        }
      } catch (e) {
        console.error('[AI Detection] failure:', e.message);
        out.warnings.push("AI detection failed");
      }

      // 4. SOURCE TRACING
      try {
        const tracingLimit = Math.min(3, selectedParagraphs.length);
        const traces = [];
        for (let i = 0; i < tracingLimit; i++) {
          const pText = selectedParagraphs[i];
          if (pText.length < 50) continue;
          
          try {
            const q = await runGroqRaw(groqKey, `Extract a 5-6 word academic search query from this paragraph. Output the query text only, nothing else:\n\n${pText.slice(0, 800)}`);
            
            // Execute both searches in parallel
            const [ss, arxivXml] = await Promise.all([
              searchSemanticScholar(q).catch(() => ({ data: [] })),
              searchArxiv(q).catch(() => '')
            ]);
            
            const arxiv = parseArxivXml(arxivXml);
            
            traces.push({
              paragraph_id: i + 1,
              paragraph_preview: pText.slice(0, 150) + "...",
              search_query_used: q,
              semantic_scholar_matches: ss?.data || [],
              arxiv_matches: arxiv
            });
            
            if (i < tracingLimit - 1) await sleep(400); // Small buffer between iterations
          } catch (e) {
             console.error(`[Source Tracing] Paragraph ${i+1} failed:`, e.message);
          }
        }
        
        if (traces.length > 0) {
          let hasMatches = traces.some(t => t.semantic_scholar_matches.length > 0 || t.arxiv_matches.length > 0);
          out.sourceTracing = {
            paragraph_traces: traces,
            stitching_analysis: {
              verdict: hasMatches ? "⚠️ Potential Source Matches Detected" : "✅ No Direct Source Matches",
              summary: `Traced ${traces.length} paragraphs. ${hasMatches ? 'Identified potential overlapping content in academic literature.' : 'Document exhibits high original research pattern.'}`,
              confidence: hasMatches ? "medium" : "high",
              stitching_detected: hasMatches,
              distinct_source_count: traces.reduce((acc, t) => acc + (t.semantic_scholar_matches.length + t.arxiv_matches.length), 0)
            }
          };
        } else {
           out.sourceTracing = { paragraph_traces: [], stitching_analysis: null };
        }
      } catch (e) {
         out.warnings.push("Source tracing failed entirely");
      }

      return new Response(JSON.stringify(out), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    return new Response(JSON.stringify({ error: 'Invalid action, expected action="analyze"' }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('[Analyze Function] Error:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});


